Fix some warnings due to type issues
Summary:
Fix some warnings due to type issues.

Fixes those two warnings:

In file included from <command-line>:
libc/sysdeps/linux/common/openat64.c:18:33: warning: 'openat64' alias between functions of incompatible types 'int(int,  const char *, int,  ...)' and 'int(int,  const char *, int,  mode_t)' {aka 'int(int,  const char *, int,  unsigned int)'} [-Wattribute-alias=]
   18 | strong_alias_untyped(__openat64,openat64)
      |                                 ^~~~~~~~
./include/libc-symbols.h:177:31: note: in definition of macro '_strong_alias_untyped'
  177 |   extern __typeof (aliasname) aliasname __attribute__ ((alias (#name))) __attribute_copy__ (name);
      |                               ^~~~~~~~~
libc/sysdeps/linux/common/openat64.c:18:1: note: in expansion of macro 'strong_alias_untyped'
   18 | strong_alias_untyped(__openat64,openat64)
      | ^~~~~~~~~~~~~~~~~~~~
libc/sysdeps/linux/common/openat64.c:14:12: note: aliased declaration here
   14 | static int __openat64(int fd, const char *file, int oflag, mode_t mode)
      |            ^~~~~~~~~~

and

  CC libc/sysdeps/linux/common/stat.os
libc/sysdeps/linux/common/stat.c: In function 'stat':
libc/sysdeps/linux/common/stat.c:28:40: warning: passing argument 3 of 'fstatat64' from incompatible pointer type [-Wincompatible-pointer-types]
   28 |  return fstatat64(AT_FDCWD, file_name, buf, 0);
      |                                        ^~~
      |                                        |
      |                                        struct stat *
In file included from libc/sysdeps/linux/common/stat.c:11:
./include/sys/stat.h:258:35: note: expected 'struct stat64 * restrict' but argument is of type 'struct stat *'
  258 |         struct stat64 *__restrict __buf, int __flag)
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~

Test Plan: run uclibc-ng testsuite

Reviewers: O52 Linux libcs Coolidge, jmaselbas

Reviewed By: O52 Linux libcs Coolidge, jmaselbas

Subscribers: #linux_coolidge_cc

Differential Revision: https://phab.kalray.eu/D15762